### PR TITLE
New donor rank system, hex codes for all rank colours

### PR DESCRIPTION
**Pull request by Asheiou**
The BGSP ranks should increase the willingness of people to purchase a rank
Hex codes let us stand out more

### CODE REVIEW

**Comment by Asheiou** [comment]
Also a builder rank that inherits worldedit and nothing else to be given alongside member to builders

**Comment by SiggiIO** [comment]
The bronze and builder lines are space separated and not tab separated.  This needs to be fixed first before we can merge!

**Comment by SiggiIO** [comment]
The essentials.sethome.multiple is required to set multiple homes.  Giving essentials.sethome.multiple.x does not automatically give essentials.sethome.multiple.

**Comment by Asheiou** [comment]
> The essentials.sethome.multiple is required to set multiple homes. Giving essentials.sethome.multiple.x does not automatically give essentials.sethome.multiple.

Gold inherits silver, it's given with silver

**Pull request merged**
